package com.dabomstew.pkrandom.constants;

/*----------------------------------------------------------------------------*/
/*--  Items.java - defines an index number constant for every item in the   --*/
/*--               game from Diamond/Pearl to Sword/Shield.                 --*/
/*--                                                                        --*/
/*--  Part of "Universal Pokemon Randomizer ZX" by the UPR-ZX team          --*/
/*--  Pokemon and any associated names and the like are                     --*/
/*--  trademark and (C) Nintendo 1996-2020.                                 --*/
/*--                                                                        --*/
/*--  The custom code written here is licensed under the terms of the GPL:  --*/
/*--                                                                        --*/
/*--  This program is free software: you can redistribute it and/or modify  --*/
/*--  it under the terms of the GNU General Public License as published by  --*/
/*--  the Free Software Foundation, either version 3 of the License, or     --*/
/*--  (at your option) any later version.                                   --*/
/*--                                                                        --*/
/*--  This program is distributed in the hope that it will be useful,       --*/
/*--  but WITHOUT ANY WARRANTY; without even the implied warranty of        --*/
/*--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the          --*/
/*--  GNU General Public License for more details.                          --*/
/*--                                                                        --*/
/*--  You should have received a copy of the GNU General Public License     --*/
/*--  along with this program. If not, see <http://www.gnu.org/licenses/>.  --*/
/*----------------------------------------------------------------------------*/

public class Items {
    // https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_index_number_(Generation_IV)
    // https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_index_number_(Generation_V)
    // https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_index_number_(Generation_VI)
    // https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_index_number_(Generation_VII)
    // https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_index_number_(Let%27s_Go,_Pikachu!_and_Let%27s_Go,_Eevee!)
    // https://bulbapedia.bulbagarden.net/wiki/List_of_items_by_index_number_(Generation_VIII)
    // Unlike in previous generations, GameFreak was *mostly* consistent with this item list starting with Diamond and
    // Pearl. Places where they were not consistent are specifically called out in comments.

    // These items are generally available in Diamond/Pearl and onwards.
    public static final int none = 0;
    public static final int masterBall = 1;
    public static final int ultraBall = 2;
    public static final int greatBall = 3;
    public static final int pokeBall = 4;
    public static final int safariBall = 5;
    public static final int netBall = 6;
    public static final int diveBall = 7;
    public static final int nestBall = 8;
    public static final int repeatBall = 9;
    public static final int timerBall = 10;
    public static final int luxuryBall = 11;
    public static final int premierBall = 12;
    public static final int duskBall = 13;
    public static final int healBall = 14;
    public static final int quickBall = 15;
    public static final int cherishBall = 16;
    public static final int potion = 17;
    public static final int antidote = 18;
    public static final int burnHeal = 19;
    public static final int iceHeal = 20;
    public static final int awakening = 21;
    public static final int paralyzeHeal = 22;
    public static final int fullRestore = 23;
    public static final int maxPotion = 24;
    public static final int hyperPotion = 25;
    public static final int superPotion = 26;
    public static final int fullHeal = 27;
    public static final int revive = 28;
    public static final int maxRevive = 29;
    public static final int freshWater = 30;
    public static final int sodaPop = 31;
    public static final int lemonade = 32;
    public static final int moomooMilk = 33;
    public static final int energyPowder = 34;
    public static final int energyRoot = 35;
    public static final int healPowder = 36;
    public static final int revivalHerb = 37;
    public static final int ether = 38;
    public static final int maxEther = 39;
    public static final int elixir = 40;
    public static final int maxElixir = 41;
    public static final int lavaCookie = 42;
    public static final int berryJuice = 43;
    public static final int sacredAsh = 44;
    public static final int hpUp = 45;
    public static final int protein = 46;
    public static final int iron = 47;
    public static final int carbos = 48;
    public static final int calcium = 49;
    public static final int rareCandy = 50;
    public static final int ppUp = 51;
    public static final int zinc = 52;
    public static final int ppMax = 53;
    public static final int oldGateau = 54;
    public static final int guardSpec = 55;
    public static final int direHit = 56;
    public static final int xAttack = 57;
    public static final int xDefense = 58;
    public static final int xSpeed = 59;
    public static final int xAccuracy = 60;
    public static final int xSpAtk = 61;
    public static final int xSpDef = 62;
    public static final int pokeDoll = 63;
    public static final int fluffyTail = 64;
    public static final int blueFlute = 65;
    public static final int yellowFlute = 66;
    public static final int redFlute = 67;
    public static final int blackFlute = 68;
    public static final int whiteFlute = 69;
    public static final int shoalSalt = 70;
    public static final int shoalShell = 71;
    public static final int redShard = 72;
    public static final int blueShard = 73;
    public static final int yellowShard = 74;
    public static final int greenShard = 75;
    public static final int superRepel = 76;
    public static final int maxRepel = 77;
    public static final int escapeRope = 78;
    public static final int repel = 79;
    public static final int sunStone = 80;
    public static final int moonStone = 81;
    public static final int fireStone = 82;
    public static final int thunderStone = 83;
    public static final int waterStone = 84;
    public static final int leafStone = 85;
    public static final int tinyMushroom = 86;
    public static final int bigMushroom = 87;
    public static final int pearl = 88;
    public static final int bigPearl = 89;
    public static final int stardust = 90;
    public static final int starPiece = 91;
    public static final int nugget = 92;
    public static final int heartScale = 93;
    public static final int honey = 94;
    public static final int growthMulch = 95;
    public static final int dampMulch = 96;
    public static final int stableMulch = 97;
    public static final int gooeyMulch = 98;
    public static final int rootFossil = 99;
    public static final int clawFossil = 100;
    public static final int helixFossil = 101;
    public static final int domeFossil = 102;
    public static final int oldAmber = 103;
    public static final int armorFossil = 104;
    public static final int skullFossil = 105;
    public static final int rareBone = 106;
    public static final int shinyStone = 107;
    public static final int duskStone = 108;
    public static final int dawnStone = 109;
    public static final int ovalStone = 110;
    public static final int oddKeystone = 111;
    public static final int griseousOrb = 112; // unused until Platinum
    public static final int tea = 113; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int unused114 = 114;
    public static final int autograph = 115; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int douseDrive = 116; // unused until Black and White
    public static final int shockDrive = 117; // unused until Black and White
    public static final int burnDrive = 118; // unused until Black and White
    public static final int chillDrive = 119; // unused until Black and White
    public static final int unused120 = 120;
    public static final int pokemonBox = 121; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int medicinePocket = 122; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int tmCase = 123; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int candyJar = 124; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int powerUpPocket = 125; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int clothingTrunk = 126; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int catchingPocket = 127; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int battlePocket = 128; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int unused129 = 129;
    public static final int unused130 = 130;
    public static final int unused131 = 131;
    public static final int unused132 = 132;
    public static final int unused133 = 133;
    public static final int sweetHeart = 134; // unused until Black and White
    public static final int adamantOrb = 135;
    public static final int lustrousOrb = 136;
    public static final int mail1 = 137; // Grass Mail in Gen 4, Greet Mail in Gen 5+
    public static final int mail2 = 138; // Flame Mail in Gen 4, Favored Mail in Gen 5+
    public static final int mail3 = 139; // Bubble Mail in Gen 4, RSVP Mail in Gen 5+
    public static final int mail4 = 140; // Bloom Mail in Gen 4, Thanks Mail in Gen 5+
    public static final int mail5 = 141; // Tunnel Mail in Gen 4, Inquiry Mail in Gen 5+
    public static final int mail6 = 142; // Steel Mail in Gen 4, Like Mail in Gen 5+
    public static final int mail7 = 143; // Heart Mail in Gen 4, Reply Mail in Gen 5+
    public static final int mail8 = 144; // Snow Mail in Gen 4, Bridge Mail S in Gen 5+
    public static final int mail9 = 145; // Space Mail in Gen 4, Bridge Mail D in Gen 5+
    public static final int mail10 = 146; // Air Mail in Gen 4, Bridge Mail T in Gen 5+
    public static final int mail11 = 147; // Mosaic Mail in Gen 4, Bridge Mail V in Gen 5+
    public static final int mail12 = 148; // Brick Mail in Gen 4, Bridge Mail W in Gen 5+
    public static final int cheriBerry = 149;
    public static final int chestoBerry = 150;
    public static final int pechaBerry = 151;
    public static final int rawstBerry = 152;
    public static final int aspearBerry = 153;
    public static final int leppaBerry = 154;
    public static final int oranBerry = 155;
    public static final int persimBerry = 156;
    public static final int lumBerry = 157;
    public static final int sitrusBerry = 158;
    public static final int figyBerry = 159;
    public static final int wikiBerry = 160;
    public static final int magoBerry = 161;
    public static final int aguavBerry = 162;
    public static final int iapapaBerry = 163;
    public static final int razzBerry = 164;
    public static final int blukBerry = 165;
    public static final int nanabBerry = 166;
    public static final int wepearBerry = 167;
    public static final int pinapBerry = 168;
    public static final int pomegBerry = 169;
    public static final int kelpsyBerry = 170;
    public static final int qualotBerry = 171;
    public static final int hondewBerry = 172;
    public static final int grepaBerry = 173;
    public static final int tamatoBerry = 174;
    public static final int cornnBerry = 175;
    public static final int magostBerry = 176;
    public static final int rabutaBerry = 177;
    public static final int nomelBerry = 178;
    public static final int spelonBerry = 179;
    public static final int pamtreBerry = 180;
    public static final int watmelBerry = 181;
    public static final int durinBerry = 182;
    public static final int belueBerry = 183;
    public static final int occaBerry = 184;
    public static final int passhoBerry = 185;
    public static final int wacanBerry = 186;
    public static final int rindoBerry = 187;
    public static final int yacheBerry = 188;
    public static final int chopleBerry = 189;
    public static final int kebiaBerry = 190;
    public static final int shucaBerry = 191;
    public static final int cobaBerry = 192;
    public static final int payapaBerry = 193;
    public static final int tangaBerry = 194;
    public static final int chartiBerry = 195;
    public static final int kasibBerry = 196;
    public static final int habanBerry = 197;
    public static final int colburBerry = 198;
    public static final int babiriBerry = 199;
    public static final int chilanBerry = 200;
    public static final int liechiBerry = 201;
    public static final int ganlonBerry = 202;
    public static final int salacBerry = 203;
    public static final int petayaBerry = 204;
    public static final int apicotBerry = 205;
    public static final int lansatBerry = 206;
    public static final int starfBerry = 207;
    public static final int enigmaBerry = 208;
    public static final int micleBerry = 209;
    public static final int custapBerry = 210;
    public static final int jabocaBerry = 211;
    public static final int rowapBerry = 212;
    public static final int brightPowder = 213;
    public static final int whiteHerb = 214;
    public static final int machoBrace = 215;
    public static final int expShare = 216; // Changed into a key item in X/Y
    public static final int quickClaw = 217;
    public static final int sootheBell = 218;
    public static final int mentalHerb = 219;
    public static final int choiceBand = 220;
    public static final int kingsRock = 221;
    public static final int silverPowder = 222;
    public static final int amuletCoin = 223;
    public static final int cleanseTag = 224;
    public static final int soulDew = 225;
    public static final int deepSeaTooth = 226;
    public static final int deepSeaScale = 227;
    public static final int smokeBall = 228;
    public static final int everstone = 229;
    public static final int focusBand = 230;
    public static final int luckyEgg = 231;
    public static final int scopeLens = 232;
    public static final int metalCoat = 233;
    public static final int leftovers = 234;
    public static final int dragonScale = 235;
    public static final int lightBall = 236;
    public static final int softSand = 237;
    public static final int hardStone = 238;
    public static final int miracleSeed = 239;
    public static final int blackGlasses = 240;
    public static final int blackBelt = 241;
    public static final int magnet = 242;
    public static final int mysticWater = 243;
    public static final int sharpBeak = 244;
    public static final int poisonBarb = 245;
    public static final int neverMeltIce = 246;
    public static final int spellTag = 247;
    public static final int twistedSpoon = 248;
    public static final int charcoal = 249;
    public static final int dragonFang = 250;
    public static final int silkScarf = 251;
    public static final int upgrade = 252;
    public static final int shellBell = 253;
    public static final int seaIncense = 254;
    public static final int laxIncense = 255;
    public static final int luckyPunch = 256;
    public static final int metalPowder = 257;
    public static final int thickClub = 258;
    public static final int leek = 259; // called "Stick" prior to SwSh
    public static final int redScarf = 260;
    public static final int blueScarf = 261;
    public static final int pinkScarf = 262;
    public static final int greenScarf = 263;
    public static final int yellowScarf = 264;
    public static final int wideLens = 265;
    public static final int muscleBand = 266;
    public static final int wiseGlasses = 267;
    public static final int expertBelt = 268;
    public static final int lightClay = 269;
    public static final int lifeOrb = 270;
    public static final int powerHerb = 271;
    public static final int toxicOrb = 272;
    public static final int flameOrb = 273;
    public static final int quickPowder = 274;
    public static final int focusSash = 275;
    public static final int zoomLens = 276;
    public static final int metronome = 277;
    public static final int ironBall = 278;
    public static final int laggingTail = 279;
    public static final int destinyKnot = 280;
    public static final int blackSludge = 281;
    public static final int icyRock = 282;
    public static final int smoothRock = 283;
    public static final int heatRock = 284;
    public static final int dampRock = 285;
    public static final int gripClaw = 286;
    public static final int choiceScarf = 287;
    public static final int stickyBarb = 288;
    public static final int powerBracer = 289;
    public static final int powerBelt = 290;
    public static final int powerLens = 291;
    public static final int powerBand = 292;
    public static final int powerAnklet = 293;
    public static final int powerWeight = 294;
    public static final int shedShell = 295;
    public static final int bigRoot = 296;
    public static final int choiceSpecs = 297;
    public static final int flamePlate = 298;
    public static final int splashPlate = 299;
    public static final int zapPlate = 300;
    public static final int meadowPlate = 301;
    public static final int iciclePlate = 302;
    public static final int fistPlate = 303;
    public static final int toxicPlate = 304;
    public static final int earthPlate = 305;
    public static final int skyPlate = 306;
    public static final int mindPlate = 307;
    public static final int insectPlate = 308;
    public static final int stonePlate = 309;
    public static final int spookyPlate = 310;
    public static final int dracoPlate = 311;
    public static final int dreadPlate = 312;
    public static final int ironPlate = 313;
    public static final int oddIncense = 314;
    public static final int rockIncense = 315;
    public static final int fullIncense = 316;
    public static final int waveIncense = 317;
    public static final int roseIncense = 318;
    public static final int luckIncense = 319;
    public static final int pureIncense = 320;
    public static final int protector = 321;
    public static final int electirizer = 322;
    public static final int magmarizer = 323;
    public static final int dubiousDisc = 324;
    public static final int reaperCloth = 325;
    public static final int razorClaw = 326;
    public static final int razorFang = 327;
    public static final int tm01 = 328;
    public static final int tm02 = 329;
    public static final int tm03 = 330;
    public static final int tm04 = 331;
    public static final int tm05 = 332;
    public static final int tm06 = 333;
    public static final int tm07 = 334;
    public static final int tm08 = 335;
    public static final int tm09 = 336;
    public static final int tm10 = 337;
    public static final int tm11 = 338;
    public static final int tm12 = 339;
    public static final int tm13 = 340;
    public static final int tm14 = 341;
    public static final int tm15 = 342;
    public static final int tm16 = 343;
    public static final int tm17 = 344;
    public static final int tm18 = 345;
    public static final int tm19 = 346;
    public static final int tm20 = 347;
    public static final int tm21 = 348;
    public static final int tm22 = 349;
    public static final int tm23 = 350;
    public static final int tm24 = 351;
    public static final int tm25 = 352;
    public static final int tm26 = 353;
    public static final int tm27 = 354;
    public static final int tm28 = 355;
    public static final int tm29 = 356;
    public static final int tm30 = 357;
    public static final int tm31 = 358;
    public static final int tm32 = 359;
    public static final int tm33 = 360;
    public static final int tm34 = 361;
    public static final int tm35 = 362;
    public static final int tm36 = 363;
    public static final int tm37 = 364;
    public static final int tm38 = 365;
    public static final int tm39 = 366;
    public static final int tm40 = 367;
    public static final int tm41 = 368;
    public static final int tm42 = 369;
    public static final int tm43 = 370;
    public static final int tm44 = 371;
    public static final int tm45 = 372;
    public static final int tm46 = 373;
    public static final int tm47 = 374;
    public static final int tm48 = 375;
    public static final int tm49 = 376;
    public static final int tm50 = 377;
    public static final int tm51 = 378;
    public static final int tm52 = 379;
    public static final int tm53 = 380;
    public static final int tm54 = 381;
    public static final int tm55 = 382;
    public static final int tm56 = 383;
    public static final int tm57 = 384;
    public static final int tm58 = 385;
    public static final int tm59 = 386;
    public static final int tm60 = 387;
    public static final int tm61 = 388;
    public static final int tm62 = 389;
    public static final int tm63 = 390;
    public static final int tm64 = 391;
    public static final int tm65 = 392;
    public static final int tm66 = 393;
    public static final int tm67 = 394;
    public static final int tm68 = 395;
    public static final int tm69 = 396;
    public static final int tm70 = 397;
    public static final int tm71 = 398;
    public static final int tm72 = 399;
    public static final int tm73 = 400;
    public static final int tm74 = 401;
    public static final int tm75 = 402;
    public static final int tm76 = 403;
    public static final int tm77 = 404;
    public static final int tm78 = 405;
    public static final int tm79 = 406;
    public static final int tm80 = 407;
    public static final int tm81 = 408;
    public static final int tm82 = 409;
    public static final int tm83 = 410;
    public static final int tm84 = 411;
    public static final int tm85 = 412;
    public static final int tm86 = 413;
    public static final int tm87 = 414;
    public static final int tm88 = 415;
    public static final int tm89 = 416;
    public static final int tm90 = 417;
    public static final int tm91 = 418;
    public static final int tm92 = 419;
    public static final int hm01 = 420;
    public static final int hm02 = 421;
    public static final int hm03 = 422;
    public static final int hm04 = 423;
    public static final int hm05 = 424;
    public static final int hm06 = 425;
    public static final int hm07 = 426; // unused after Gen 4
    public static final int hm08 = 427; // unused after Gen 4
    public static final int explorerKit = 428; // unused in HeartGold and SoulSilver
    public static final int lootSack = 429;
    public static final int ruleBook = 430;
    public static final int pokeRadar = 431;
    public static final int pointCard = 432;
    public static final int journal = 433;
    public static final int sealCase = 434;
    public static final int fashionCase = 435;
    public static final int sealBag = 436;
    public static final int palPad = 437;
    public static final int worksKey = 438;
    public static final int oldCharm = 439;
    public static final int galacticKey = 440;
    public static final int redChain = 441;
    public static final int townMap = 442;
    public static final int vsSeeker = 443;
    public static final int coinCase = 444;
    public static final int oldRod = 445;
    public static final int goodRod = 446;
    public static final int superRod = 447;
    public static final int sprayduck = 448;
    public static final int poffinCase = 449;
    public static final int bike = 450; // Green Bicycle in X/Y
    public static final int suiteKey = 451;
    public static final int oaksLetter = 452;
    public static final int lunarWing = 453;
    public static final int memberCard = 454;
    public static final int azureFlute = 455;
    public static final int ssTicketJohto = 456;
    public static final int contestPass = 457;
    public static final int magmaStone = 458;
    public static final int parcelSinnoh = 459;
    public static final int coupon1 = 460;
    public static final int coupon2 = 461;
    public static final int coupon3 = 462;
    public static final int storageKeySinnoh = 463;
    public static final int secretPotion = 464;

    // These items are generally available in Platinum and onwards.
    public static final int vsRecorder = 465;
    public static final int gracidea = 466;
    public static final int secretKeySinnoh = 467;

    // These items are generally available in HeartGold/SoulSilver and onwards.
    public static final int apricornBox = 468;
    public static final int unownReport = 469;
    public static final int berryPots = 470;
    public static final int dowsingMachine = 471;
    public static final int blueCard = 472;
    public static final int slowpokeTail = 473;
    public static final int clearBell = 474;
    public static final int cardKeyJohto = 475;
    public static final int basementKeyJohto = 476;
    public static final int squirtBottle = 477;
    public static final int redScale = 478;
    public static final int lostItem = 479;
    public static final int pass = 480;
    public static final int machinePart = 481;
    public static final int silverWing = 482;
    public static final int rainbowWing = 483;
    public static final int mysteryEgg = 484;
    public static final int redApricorn = 485;
    public static final int blueApricorn = 486;
    public static final int yellowApricorn = 487;
    public static final int greenApricorn = 488;
    public static final int pinkApricorn = 489;
    public static final int whiteApricorn = 490;
    public static final int blackApricorn = 491;
    public static final int fastBall = 492;
    public static final int levelBall = 493;
    public static final int lureBall = 494;
    public static final int heavyBall = 495;
    public static final int loveBall = 496;
    public static final int friendBall = 497;
    public static final int moonBall = 498;
    public static final int sportBall = 499;
    public static final int parkBall = 500;
    public static final int photoAlbum = 501;
    public static final int gbSounds = 502;
    public static final int tidalBell = 503;
    public static final int rageCandyBar = 504;

    // Expansion
    public static final int golurkite = 505;
    public static final int crabominite = 506;
    public static final int golisopite = 507;
    public static final int zeraorite = 508;
    public static final int scovillainite = 509;
    public static final int baxcalibrite = 510;
    public static final int glimmoranite = 511;
    public static final int absoliteZ = 512;
    public static final int garchompiteZ = 513;
    public static final int lucarioniteZ = 514;
    public static final int greninjite = 515;
    public static final int floettite = 516;
    public static final int zygardite = 517;
    public static final int meowsticite = 518;
    public static final int magearnite = 519;
    public static final int tatsugirinite = 520;
    
    public static final int dataCard17 = 521;
    public static final int dataCard18 = 522;
    public static final int dataCard19 = 523;
    public static final int dataCard20 = 524;
    public static final int dataCard21 = 525;
    public static final int dataCard22 = 526;
    public static final int dataCard23 = 527;
    public static final int dataCard24 = 528;
    public static final int dataCard25 = 529;
    public static final int dataCard26 = 530;
    public static final int dataCard27 = 531;
    public static final int jadeOrb = 532;
    public static final int lockCapsule = 533;
    public static final int redOrb = 534; // Changed into a held item in Omega Ruby/Alpha Sapphire
    public static final int blueOrb = 535; // Changed into a held item in Omega Ruby/Alpha Sapphire
    public static final int enigmaStone = 536;

    // These items are generally available in Black/White and onwards
    public static final int prismScale = 537;
    public static final int eviolite = 538;
    public static final int floatStone = 539;
    public static final int rockyHelmet = 540;
    public static final int airBalloon = 541;
    public static final int redCard = 542;
    public static final int ringTarget = 543;
    public static final int bindingBand = 544;
    public static final int absorbBulb = 545;
    public static final int cellBattery = 546;
    public static final int ejectButton = 547;
    public static final int fireGem = 548;
    public static final int waterGem = 549;
    public static final int electricGem = 550;
    public static final int grassGem = 551;
    public static final int iceGem = 552;
    public static final int fightingGem = 553;
    public static final int poisonGem = 554;
    public static final int groundGem = 555;
    public static final int flyingGem = 556;
    public static final int psychicGem = 557;
    public static final int bugGem = 558;
    public static final int rockGem = 559;
    public static final int ghostGem = 560;
    public static final int dragonGem = 561;
    public static final int darkGem = 562;
    public static final int steelGem = 563;
    public static final int normalGem = 564;
    public static final int healthFeather = 565;
    public static final int muscleFeather = 566;
    public static final int resistFeather = 567;
    public static final int geniusFeather = 568;
    public static final int cleverFeather = 569;
    public static final int swiftFeather = 570;
    public static final int prettyFeather = 571;
    public static final int coverFossil = 572;
    public static final int plumeFossil = 573;
    public static final int libertyPass = 574;
    public static final int passOrb = 575;
    public static final int dreamBall = 576;
    public static final int pokeToy = 577;
    public static final int propCase = 578;
    public static final int dragonSkull = 579;
    public static final int balmMushroom = 580;
    public static final int bigNugget = 581;
    public static final int pearlString = 582;
    public static final int cometShard = 583;
    public static final int relicCopper = 584;
    public static final int relicSilver = 585;
    public static final int relicGold = 586;
    public static final int relicVase = 587;
    public static final int relicBand = 588;
    public static final int relicStatue = 589;
    public static final int relicCrown = 590;
    public static final int casteliacone = 591;
    public static final int direHit2 = 592;
    public static final int xSpeed2 = 593;
    public static final int xSpAtk2 = 594;
    public static final int xSpDef2 = 595;
    public static final int xDefense2 = 596;
    public static final int xAttack2 = 597;
    public static final int xAccuracy2 = 598;
    public static final int xSpeed3 = 599;
    public static final int xSpAtk3 = 600;
    public static final int xSpDef3 = 601;
    public static final int xDefense3 = 602;
    public static final int xAttack3 = 603;
    public static final int xAccuracy3 = 604;
    public static final int xSpeed6 = 605;
    public static final int xSpAtk6 = 606;
    public static final int xSpDef6 = 607;
    public static final int xDefense6 = 608;
    public static final int xAttack6 = 609;
    public static final int xAccuracy6 = 610;
    public static final int abilityUrge = 611;
    public static final int itemDrop = 612;
    public static final int itemUrge = 613;
    public static final int resetUrge = 614;
    public static final int direHit3 = 615;
    public static final int lightStone = 616;
    public static final int darkStone = 617;
    public static final int tm93 = 618;
    public static final int tm94 = 619;
    public static final int tm95 = 620;
    public static final int xtransceiverMale = 621;
    public static final int unused622 = 622;
    public static final int gram1 = 623;
    public static final int gram2 = 624;
    public static final int gram3 = 625;
    public static final int xtransceiverFemale = 626;

    // These items are generally available in Black 2/White 2 and onwards.
    public static final int medalBox = 627;
    public static final int dNASplicersFuse = 628;
    public static final int dNASplicersSeparate = 629;
    public static final int permit = 630;
    public static final int ovalCharm = 631;
    public static final int shinyCharm = 632;
    public static final int plasmaCard = 633;
    public static final int grubbyHanky = 634;
    public static final int colressMachine = 635;
    public static final int droppedItemCurtis = 636;
    public static final int droppedItemYancy = 637;
    public static final int revealGlass = 638;

    // These items are generally available in X/Y and onwards.
    public static final int weaknessPolicy = 639;
    public static final int assaultVest = 640;
    public static final int holoCasterMale = 641;
    public static final int profsLetter = 642;
    public static final int rollerSkates = 643;
    public static final int pixiePlate = 644;
    public static final int abilityCapsule = 645;
    public static final int whippedDream = 646;
    public static final int sachet = 647;
    public static final int luminousMoss = 648;
    public static final int snowball = 649;
    public static final int safetyGoggles = 650;
    public static final int pokeFlute = 651;
    public static final int richMulch = 652;
    public static final int surpriseMulch = 653;
    public static final int boostMulch = 654;
    public static final int amazeMulch = 655;
    public static final int gengarite = 656;
    public static final int gardevoirite = 657;
    public static final int ampharosite = 658;
    public static final int venusaurite = 659;
    public static final int charizarditeX = 660;
    public static final int blastoisinite = 661;
    public static final int mewtwoniteX = 662;
    public static final int mewtwoniteY = 663;
    public static final int blazikenite = 664;
    public static final int medichamite = 665;
    public static final int houndoominite = 666;
    public static final int aggronite = 667;
    public static final int banettite = 668;
    public static final int tyranitarite = 669;
    public static final int scizorite = 670;
    public static final int pinsirite = 671;
    public static final int aerodactylite = 672;
    public static final int lucarionite = 673;
    public static final int abomasite = 674;
    public static final int kangaskhanite = 675;
    public static final int gyaradosite = 676;
    public static final int absolite = 677;
    public static final int charizarditeY = 678;
    public static final int alakazite = 679;
    public static final int heracronite = 680;
    public static final int mawilite = 681;
    public static final int manectite = 682;
    public static final int garchompite = 683;
    public static final int latiasite = 684;
    public static final int latiosite = 685;
    public static final int roseliBerry = 686;
    public static final int keeBerry = 687;
    public static final int marangaBerry = 688;
    public static final int sprinklotad = 689;
    public static final int tm96 = 690;
    public static final int tm97 = 691;
    public static final int tm98 = 692;
    public static final int tm99 = 693;
    public static final int tm100 = 694;
    public static final int powerPlantPass = 695;
    public static final int megaRing = 696;
    public static final int intriguingStone = 697;
    public static final int commonStone = 698;
    public static final int discountCoupon = 699;
    public static final int elevatorKey = 700;
    public static final int tmvPass = 701;
    public static final int honorofKalos = 702;
    public static final int adventureGuide = 703;
    public static final int strangeSouvenir = 704;
    public static final int lensCase = 705;
    public static final int makeupBag = 706;
    public static final int travelTrunk = 707;
    public static final int lumioseGalette = 708;
    public static final int shalourSable = 709;
    public static final int jawFossil = 710;
    public static final int sailFossil = 711;
    public static final int lookerTicket = 712;
    public static final int bikeYellow = 713;
    public static final int holoCasterFemale = 714;
    public static final int fairyGem = 715;
    public static final int megaCharm = 716;
    public static final int megaGlove = 717;

    // These items are generally available in Omega Ruby/Alpha Sapphire and onwards.
    public static final int machBike = 718;
    public static final int acroBike = 719;
    public static final int wailmerPail = 720;
    public static final int devonParts = 721;
    public static final int sootSack = 722;
    public static final int basementKeyHoenn = 723;
    public static final int pokeblockKit = 724;
    public static final int letter = 725;
    public static final int eonTicket = 726;
    public static final int scanner = 727;
    public static final int goGoggles = 728;
    public static final int meteoriteFirstForm = 729;
    public static final int keytoRoom1 = 730;
    public static final int keytoRoom2 = 731;
    public static final int keytoRoom4 = 732;
    public static final int keytoRoom6 = 733;
    public static final int storageKeyHoenn = 734;
    public static final int devonScope = 735;
    public static final int ssTicketHoenn = 736;
    public static final int hm07ORAS = 737;
    public static final int devonScubaGear = 738;
    public static final int contestCostumeMale = 739;
    public static final int contestCostumeFemale = 740;
    public static final int magmaSuit = 741;
    public static final int aquaSuit = 742;
    public static final int pairOfTickets = 743;
    public static final int megaBracelet = 744;
    public static final int megaPendant = 745;
    public static final int megaGlasses = 746;
    public static final int megaAnchor = 747;
    public static final int megaStickpin = 748;
    public static final int megaTiara = 749;
    public static final int megaAnklet = 750;
    public static final int meteoriteSecondForm = 751;
    public static final int swampertite = 752;
    public static final int sceptilite = 753;
    public static final int sablenite = 754;
    public static final int altarianite = 755;
    public static final int galladite = 756;
    public static final int audinite = 757;
    public static final int metagrossite = 758;
    public static final int sharpedonite = 759;
    public static final int slowbronite = 760;
    public static final int steelixite = 761;
    public static final int pidgeotite = 762;
    public static final int glalitite = 763;
    public static final int diancite = 764;
    public static final int prisonBottle = 765;
    public static final int megaCuff = 766;
    public static final int cameruptite = 767;
    public static final int lopunnite = 768;
    public static final int salamencite = 769;
    public static final int beedrillite = 770;
    public static final int meteoriteThirdForm = 771;
    public static final int meteoriteFinalForm = 772;
    public static final int keyStone = 773;
    public static final int meteoriteShard = 774;
    public static final int eonFlute = 775;

    // These items are generally available in Sun/Moon and onwards.
    public static final int normaliumZHeld = 776;
    public static final int firiumZHeld = 777;
    public static final int wateriumZHeld = 778;
    public static final int electriumZHeld = 779;
    public static final int grassiumZHeld = 780;
    public static final int iciumZHeld = 781;
    public static final int fightiniumZHeld = 782;
    public static final int poisoniumZHeld = 783;
    public static final int groundiumZHeld = 784;
    public static final int flyiniumZHeld = 785;
    public static final int psychiumZHeld = 786;
    public static final int buginiumZHeld = 787;
    public static final int rockiumZHeld = 788;
    public static final int ghostiumZHeld = 789;
    public static final int dragoniumZHeld = 790;
    public static final int darkiniumZHeld = 791;
    public static final int steeliumZHeld = 792;
    public static final int fairiumZHeld = 793;
    public static final int pikaniumZHeld = 794;
    public static final int bottleCap = 795;
    public static final int goldBottleCap = 796;
    public static final int zRing = 797;
    public static final int decidiumZHeld = 798;
    public static final int inciniumZHeld = 799;
    public static final int primariumZHeld = 800;
    public static final int tapuniumZHeld = 801;
    public static final int marshadiumZHeld = 802;
    public static final int aloraichiumZHeld = 803;
    public static final int snorliumZHeld = 804;
    public static final int eeviumZHeld = 805;
    public static final int mewniumZHeld = 806;
    public static final int normaliumZBag = 807;
    public static final int firiumZBag = 808;
    public static final int wateriumZBag = 809;
    public static final int electriumZBag = 810;
    public static final int grassiumZBag = 811;
    public static final int iciumZBag = 812;
    public static final int fightiniumZBag = 813;
    public static final int poisoniumZBag = 814;
    public static final int groundiumZBag = 815;
    public static final int flyiniumZBag = 816;
    public static final int psychiumZBag = 817;
    public static final int buginiumZBag = 818;
    public static final int rockiumZBag = 819;
    public static final int ghostiumZBag = 820;
    public static final int dragoniumZBag = 821;
    public static final int darkiniumZBag = 822;
    public static final int steeliumZBag = 823;
    public static final int fairiumZBag = 824;
    public static final int pikaniumZBag = 825;
    public static final int decidiumZBag = 826;
    public static final int inciniumZBag = 827;
    public static final int primariumZBag = 828;
    public static final int tapuniumZBag = 829;
    public static final int marshadiumZBag = 830;
    public static final int aloraichiumZBag = 831;
    public static final int snorliumZBag = 832;
    public static final int eeviumZBag = 833;
    public static final int mewniumZBag = 834;
    public static final int pikashuniumZHeld = 835;
    public static final int pikashuniumZBag = 836;
    public static final int unused837 = 837;
    public static final int unused838 = 838;
    public static final int unused839 = 839;
    public static final int unused840 = 840;
    public static final int forageBag = 841;
    public static final int fishingRod = 842;
    public static final int professorsMask = 843;
    public static final int festivalTicket = 844;
    public static final int sparklingStone = 845;
    public static final int adrenalineOrb = 846;
    public static final int zygardeCube = 847;
    public static final int unused848 = 848;
    public static final int iceStone = 849;
    public static final int ridePager = 850;
    public static final int beastBall = 851;
    public static final int bigMalasada = 852;
    public static final int redNectar = 853;
    public static final int yellowNectar = 854;
    public static final int pinkNectar = 855;
    public static final int purpleNectar = 856;
    public static final int sunFlute = 857;
    public static final int moonFlute = 858;
    public static final int unused859 = 859;
    public static final int enigmaticCard = 860;
    public static final int silverRazzBerry = 861; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int goldenRazzBerry = 862; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int silverNanabBerry = 863; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int goldenNanabBerry = 864; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int silverPinapBerry = 865; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int goldenPinapBerry = 866; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int unused867 = 867;
    public static final int unused868 = 868;
    public static final int unused869 = 869;
    public static final int unused870 = 870;
    public static final int unused871 = 871;
    public static final int secretKeyKanto = 872; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int ssTicketKanto = 873; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int silphScope = 874; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int parcelKanto = 875; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int cardKeyKanto = 876; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int goldTeeth = 877; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int liftKey = 878; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int terrainExtender = 879;
    public static final int protectivePads = 880;
    public static final int electricSeed = 881;
    public static final int psychicSeed = 882;
    public static final int mistySeed = 883;
    public static final int grassySeed = 884;
    public static final int stretchySpring = 885; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int chalkyStone = 886; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int marble = 887; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int loneEarring = 888; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int beachGlass = 889; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int goldLeaf = 890; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int silverLeaf = 891; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int polishedMudBall = 892; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int tropicalShell = 893; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int leafLetterPikachu = 894; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int leafLetterEevee = 895; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int smallBouquet = 896; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int unused897 = 897;
    public static final int unused898 = 898;
    public static final int unused899 = 899;
    public static final int lure = 900; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int superLure = 901; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int maxLure = 902; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int pewterCrunchies = 903; // unused until Let's Go Pikachu/Let's Go Eevee
    public static final int fightingMemory = 904;
    public static final int flyingMemory = 905;
    public static final int poisonMemory = 906;
    public static final int groundMemory = 907;
    public static final int rockMemory = 908;
    public static final int bugMemory = 909;
    public static final int ghostMemory = 910;
    public static final int steelMemory = 911;
    public static final int fireMemory = 912;
    public static final int waterMemory = 913;
    public static final int grassMemory = 914;
    public static final int electricMemory = 915;
    public static final int psychicMemory = 916;
    public static final int iceMemory = 917;
    public static final int dragonMemory = 918;
    public static final int darkMemory = 919;
    public static final int fairyMemory = 920;

    // These items are generally available in Ultra Sun/Ultra Moon and onwards.
    public static final int solganiumZBag = 921;
    public static final int lunaliumZBag = 922;
    public static final int ultranecroziumZBag = 923;
    public static final int mimikiumZHeld = 924;
    public static final int lycaniumZHeld = 925;
    public static final int kommoniumZHeld = 926;
    public static final int solganiumZHeld = 927;
    public static final int lunaliumZHeld = 928;
    public static final int ultranecroziumZHeld = 929;
    public static final int mimikiumZBag = 930;
    public static final int lycaniumZBag = 931;
    public static final int kommoniumZBag = 932;
    public static final int zPowerRing = 933;
    public static final int pinkPetal = 934;
    public static final int orangePetal = 935;
    public static final int bluePetal = 936;
    public static final int redPetal = 937;
    public static final int greenPetal = 938;
    public static final int yellowPetal = 939;
    public static final int purplePetal = 940;
    public static final int rainbowFlower = 941;
    public static final int surgeBadge = 942;
    public static final int nSolarizerFuse = 943;
    public static final int nLunarizerFuse = 944;
    public static final int nSolarizerSeparate = 945;
    public static final int nLunarizerSeparate = 946;
    public static final int ilimaNormaliumZ = 947;
    public static final int leftPokeBall = 948;
    public static final int rotoHatch = 949;
    public static final int rotoBargain = 950;
    public static final int rotoPrizeMoney = 951;
    public static final int rotoExpPoints = 952;
    public static final int rotoFriendship = 953;
    public static final int rotoEncounter = 954;
    public static final int rotoStealth = 955;
    public static final int rotoHPRestore = 956;
    public static final int rotoPPRestore = 957;
    public static final int rotoBoost = 958;
    public static final int rotoCatch = 959;

    // Expansion
    public static final int boosterEnergy = 960;
    public static final int eternatusite = 961;
    public static final int teraCrystal = 962;
    public static final int rustedSword = 963;
    public static final int rustedShield = 964;
    public static final int reinsofUnity = 965;
    public static final int adamantCrystal = 966;
    public static final int lustrousGlobe = 967;
    public static final int wellspringMask = 968;
    public static final int hearthflameMask = 969;
    public static final int cornerstoneMask = 970;
    public static final int galaricaCuff = 971;
    public static final int galaricaWreath = 972;
    public static final int tartApple = 973;
    public static final int sweetApple = 974;
    public static final int crackedPot = 975;
    public static final int chippedPot = 976;
    public static final int strawberrySweet = 977;
    public static final int berrySweet = 978;
    public static final int loveSweet = 979;
    public static final int starSweet = 980;
    public static final int cloverSweet = 981;
    public static final int flowerSweet = 982;
    public static final int ribbonSweet = 983;
    public static final int darknessScroll = 984;
    public static final int scrollofWaters = 985;
    public static final int blackAugurite = 986;
    public static final int peatBlock = 987;
    public static final int auspiciousArmor = 988;
    public static final int maliciousArmor = 989;
    public static final int leadersCrest = 990;
    public static final int syrupyApple = 991;
    public static final int unremarkableCup = 992;
    public static final int masterpieceCup = 993;
    public static final int gimmighoulCoin = 994;
    public static final int raichuniteX = 995;
    public static final int raichuniteY = 996;
    public static final int clefablite = 997;
    public static final int victreebelite = 998;
    public static final int starminite = 999;
    public static final int dragoninite = 1000;
    public static final int meganiumite = 1001;
    public static final int feraligite = 1002;
    public static final int skarmorite = 1003;
    public static final int froslassite = 1004;
    public static final int emboarite = 1005;
    public static final int excadrite = 1006;
    public static final int scolipite = 1007;
    public static final int scraftinite = 1008;
    public static final int eelektrossite = 1009;
    public static final int chandelurite = 1010;
    public static final int chesnaughtite = 1011;
    public static final int delphoxite = 1012;
    public static final int pyroarite = 1013;
    public static final int malamarite = 1014;
    public static final int barbaracite = 1015;
    public static final int dragalgite = 1016;
    public static final int hawluchanite = 1017;
    public static final int drampanite = 1018;
    public static final int falinksite = 1019;
    public static final int chimechite = 1020;
    public static final int staraptite = 1021;
    public static final int heatranite = 1022;
    public static final int darkranite = 1023;
}
